"""add count column to association table

Revision ID: 96f200c5ce0b
Revises: 6b0e6bfbd919
Create Date: 2024-11-24 17:50:29.166679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f200c5ce0b'
down_revision: Union[str, None] = '6b0e6bfbd919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_product_association',
        sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'count')
    # ### end Alembic commands ###
