"""add column unit_price

Revision ID: 7c111a4e0245
Revises: 96f200c5ce0b
Create Date: 2024-11-26 20:28:03.189905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c111a4e0245'
down_revision: Union[str, None] = '96f200c5ce0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_product_association',
        sa.Column('unit_price',
        sa.Integer(),
        server_default='0',
        nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'unit_price')
    # ### end Alembic commands ###
